name: Build Solution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Укажите версию .NET Core, которая подходит для всех ваших проектов

    - name: Restore NuGet packages for .NET Framework 4.8
      run: |
        cd ImageUploader.DesktopClient
        dotnet restore

    - name: Build Solution for .NET Framework 4.8
      run: |
        cd ImageUploader.DesktopClient
        dotnet build --configuration Release

    - name: Restore NuGet packages for .NET Standard 2.0
      run: |
        cd ImageUploader.DesktopCommon
        dotnet restore

    - name: Build Solution for .NET Standard 2.0
      run: |
        cd ImageUploader.DesktopCommon
        dotnet build --configuration Release

    - name: Restore NuGet packages for .NET Core 2.0
      run: |
        cd ImageUploader.Gateway
        dotnet restore

    - name: Build Solution for .NET Core 2.0
      run: |
        cd ImageUploader.Gateway
        dotnet build --configuration Release

    - name: Restore NuGet packages for .NET 6.0
      run: |
        cd ImageUploader.ModernDesktopClient
        dotnet restore

    - name: Build Solution for .NET 6.0
      run: |
        cd ImageUploader.ModernDesktopClient
        dotnet build --configuration Release
