name: Build Solution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages for .NET Framework 4.8
        run: |
          cd ImageUploader.DesktopClient
          dotnet restore

      - name: Build Solution for .NET Framework 4.8
        run: |
          cd ImageUploader.DesktopClient
          dotnet build --configuration Release

      - name: Restore NuGet packages for .NET Standard 2.0
        run: |
          cd ImageUploader.DesktopCommon
          dotnet restore

      - name: Build Solution for .NET Standard 2.0
        run: |
          cd ImageUploader.DesktopCommon
          dotnet build --configuration Release

      - name: Restore NuGet packages for .NET Core 2.0
        run: |
          cd ImageUploader.Gateway
          dotnet restore

      - name: Build Solution for .NET Core 2.0
        run: |
          cd ImageUploader.Gateway
          dotnet build --configuration Release

      - name: Restore NuGet packages for .NET 6.0
        run: |
          cd ImageUploader.ModernDesktopClient
          dotnet restore

      - name: Build Solution for .NET 6.0
        run: |
          cd ImageUploader.ModernDesktopClient
          dotnet build --configuration Release

      # Debugging steps
      - name: List files in DesktopClient/bin/Release/
        run: |
          ls -l ImageUploader.DesktopClient/bin/Release/
      - name: List files in DesktopCommon/bin/Release/
        run: |
          ls -l ImageUploader.DesktopCommon/bin/Release/
      - name: List files in Gateway/bin/Release/
        run: |
          ls -l ImageUploader.Gateway/bin/Release/
      - name: List files in ModernDesktopClient/bin/Release/
        run: |
          ls -l ImageUploader.ModernDesktopClient/bin/Release/

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-files
          path: |
            ImageUploader.DesktopClient/bin/Release/
            ImageUploader.DesktopCommon/bin/Release/
            ImageUploader.Gateway/bin/Release/
            ImageUploader.ModernDesktopClient/bin/Release/
